register endpoint
justTill/easyStocksBackend pull request #11
Opened 2021-12-07 22:24 UTC by justTill

2021-12-07 22:52 UTC, proohit requested changes

2021-12-07 22:52 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +        //TODO: How to Return Error?
By throwing an appropriate exception :) eg BadRequest

2021-12-07 22:52 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/persistence/model/WatchlistData.java
> +    private UUID watchlistId;
Make this the Id instead

2021-12-07 22:52 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            final UUID watchlistId = UUID.randomUUID();
You can also let this auto generate if missing by db

2021-12-07 22:52 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            return new PostRegisterResponseDto(user.getId(), username, watchlistId.toString());
Todo: return token

2021-12-08 08:39 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            return new PostRegisterResponseDto(user.getId(), username, watchlistId.toString());
ich weiß nicht genau wie du das machen willst auch mit dem Login, ich würde das dann eher bei deinem Branch im Login ändern

2021-12-08 08:49 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            return new PostRegisterResponseDto(user.getId(), username, watchlistId.toString());
ich dachte daran, bei erfolgreichem login/register einfach einen validen JWT zu generieren und zurückzusenden, der dann kp für 1 monat oder so gültig ist
der wird dann vom frontend im header mitgesendet und bei jeder kontextsensitiver route validiert

2021-12-08 08:50 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            return new PostRegisterResponseDto(user.getId(), username, watchlistId.toString());
möglich wäre zb ein Filter auf den JWT über spring security oder eine @Secured annotation auf jedem secured path der dann im kontext des requests validiert und ggf. 401/403 zurückgibt

2021-12-08 09:03 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            final UUID watchlistId = UUID.randomUUID();
bekomme es nicht hin das es von Liquibase autogenerated wird, daher kann ich es auch nicht als PK machen

2021-12-08 19:47 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            final UUID watchlistId = UUID.randomUUID();
probier mal. hab ne änderung gepushed

2021-12-08 19:51 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            return new PostRegisterResponseDto(user.getId(), username, watchlistId.toString());
https://www.javainuse.com/spring/boot-jwt

2021-12-08 20:05 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            final UUID watchlistId = UUID.randomUUID();
nope kommt nh PSQLException wegen not null-constraint ( ERROR: null value in column "watchlist_id" of relation "users" violates not-null constraint)

2021-12-08 20:08 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            final UUID watchlistId = UUID.randomUUID();
Ist die Migration durchgelaufen? Die id sollte eigentlich nen default value haben , schau mal bei dbeaver was unter default bei der Spalte steht

2021-12-08 20:09 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            final UUID watchlistId = UUID.randomUUID();
ja der letzte eintrag ist von dir mit dem title generateWatchlistUUID

2021-12-15 14:25 UTC, proohit approved these changes

2021-12-15 14:26 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/controller/UserController.java
> +            return new PostRegisterResponseDto(user.getId(), username, watchlistId.toString());
TBD in anderem Branch

2021-12-15 14:26 UTC, merged