Feature/notificationsendpoint
justTill/easyStocksBackend pull request #16
Opened 2021-12-28 10:15 UTC by justTill

2022-01-04 21:07 UTC, proohit reviewed
Code sieht gut aus, werde nochmal selbst testen und dann approven 👍

2022-01-04 21:07 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
sollen wir hier den schwellenwert oder doch den tatsächlichen unterschied speichern?

2022-01-04 21:47 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
ich glaub so reicht, kann es aber auch gerne ändern

2022-01-05 18:12 UTC, proohit requested changes

2022-01-05 18:12 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
würde hier nicht `dayInterval` speichern, sondern den tatsächlichen tagesunterschied. die daten sind nicht immer perfekt vorhanden, sodass auch lücken existieren können. da mit `findFirst` auch ein anderes datum betrachtet werden kann, würde die angabe von `dayInterval` auch nicht mehr stimmen

2022-01-05 18:12 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +                .toLocalDate().minusDays(dayInterval);
das funktioniert bei mir nicht so ganz. bsp: `latestStockDataDate`=13.12.21 für `VOW3.FRK` und `latestStockDataDate`(GMT+2, daher 14.12.21)-`dayInterval`(3) = 11.12.2021. der query wird dann als Date der 11.12.21 übergeben. soweit so richtig. allerdings kommt dann ein `StockData` mit date=2.1.2005 zurück. glaub da muss einfach noch ein orderByDateDesc oder so rein. for reference, diese query schien bei mir zu funktionieren:
```sql
select * from stocks_data where symbol = 'VOW3.FRK' and date <= '11.12.21' order by date desc limit 1
```

2022-01-05 18:50 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
bitte nochmal testen

2022-01-05 18:51 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +                .toLocalDate().minusDays(dayInterval);
bitte nochmal testen

2022-01-05 19:11 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +                .toLocalDate().minusDays(dayInterval);
top, scheint zu funktionieren

2022-01-05 19:13 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
das wirft bei mir leider eine exception bei `getDayDifference`, vermutlich liegts am format.. bei mir liegen die Daten so in der DB `2021-12-14`, keine ahnung ob das einen unterschied macht
```txt
java.time.format.DateTimeParseException: Text '2021-12-14 00:00:00.0' could not be parsed at index 2
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[na:na]
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[na:na]
        at java.base/java.time.LocalDate.parse(LocalDate.java:428) ~[na:na]
        at com.mobsys.easyStocks.service.StockUpdateService.getDayDifference(StockUpdateService.java:168) ~[main/:na]
        at com.mobsys.easyStocks.service.StockUpdateService.lambda$3(StockUpdateService.java:159) ~[main/:na]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
        at com.mobsys.easyStocks.service.StockUpdateService.saveNotifications(StockUpdateService.java:152) ~[main/:na]
        at com.mobsys.easyStocks.service.StockUpdateService.updateDailyStockData(StockUpdateService.java:97) ~[main/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.12.jar:5.3.12]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.12.jar:5.3.12]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.12.jar:5.3.12]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

2022-01-05 19:19 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
gefixed

2022-01-05 19:30 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
super, danke. eine sache noch: soll das day_interval so? hab extra ganz niedrige percentage zum testen verwendet (0,05%)
<img width="805" alt="Screenshot 2022-01-05 at 8 28 37 PM" src="https://user-images.githubusercontent.com/46965017/148277150-01495f31-cdd4-43a5-8a81-32ba59b729df.png">

2022-01-05 19:32 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
hatte das so gelassen da es mit 4 Tagen in der Vergangenheit gecheckt wird, wobei das Minus kann auch weg da wir nicht in die Zukunft schauen können XD

2022-01-05 19:32 UTC, justTill commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
habe es getausch, jetzt sollte da nur 4 stehen

2022-01-05 22:49 UTC, proohit commented on src/main/java/com/mobsys/easyStocks/service/StockUpdateService.java
> +        watchlistRepository.setNotifications(tmpStock, dayInterval, percentage);
jetzt passt alles :)

2022-01-05 22:49 UTC, proohit approved these changes

2022-01-05 22:50 UTC, merged